### ISSUE TITLE
data is not complete

### ISSUE THREAD

**Issue by elipapa** [opentargets/library-beam#8]
@elipapa commented on [Mon Feb 12 2018](https://github.com/opentargets/data_pipeline/issues/255)

Here is the typical error:
![screen shot 2018-02-12 at 17 09 46](https://user-images.githubusercontent.com/112610/36110419-6b4c07b4-101a-11e8-9fca-dce5785f4cb3.png)

`curl http://35.189.243.117:39200/pubmed-18/publication/15452297?pretty`
example with a pubmed exist literature

`curl http://35.189.243.117:39200/pubmed-18/publication/29057642?pretty`
one without

---

@mkarmona commented on [Mon Feb 19 2018](https://github.com/opentargets/data_pipeline/issues/255#issuecomment-366662572)

it seems to be a mix of outdated lit database and medline number of opened publications

**Comment by afaulconbridge** [comment]
Now that I've re-run the import pipeline, these seem to be present now (e.g. 29057642). Therefore, closing this issue.
